sudo: required
language: bash
services:
  - docker

before_install:
  # Update brew catalogue if going to install anything
  - ${BREW:+brew update}

  # Install brew dependencies
  - ${BREW:+brew install ${BREW}}

script:
  - spec_shell=${spec_shell} ${spec_shell} ./coral spec $(find ${TARGET})

matrix:
  include:
    - env: spec_shell=sh TARGET="spec/README.md"
      os:  linux

    - env: spec_shell="bash" TARGET="spec/*/*"
      os:  osx

    - env: spec_shell="zsh" BREW="zsh" TARGET="spec/*/*"
      os:  osx

    - env: spec_shell="ksh" BREW="ksh" TARGET="spec/*/*"
      os:  osx

    - env: spec_shell="mksh" BREW="mksh" TARGET="spec/*/*"
      os:  osx

    - env: spec_shell="dash" BREW="dash" TARGET="spec/*/*"
      os:  osx
