language: bash
sudo: required
services:
  - docker

before_install:
  # Update brew catalogue if going to install anything
  - ${BREW:+brew update}

  # Install brew dependencies
  - ${BREW:+brew install ${BREW}}

  - ${APT:+curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -}
  - ${APT:+sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"}
  - ${APT:+sudo apt-get update}
  - ${APT:+sudo apt-get -y. install docker-ce}

  # Build spec_doc module
  - ${spec_doc_shell} ./lib/dev module_assemble module_assemble module_assemble
  - ${spec_doc_shell} ./module_assemble spec_doc spec_doc
  - chmod +x spec_doc

script:
  - spec_doc_shell="${spec_doc_shell}" ${spec_doc_shell} ./spec_doc $(find ${TARGET})

matrix:
  include:
    # All Linux builds as docker images
    - env: spec_doc_shell=sh APT="docker-ce" TARGET="doc/test/*"
      os:  linux

    # OS X Targeted Builds
    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9.3

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9.2

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9.1

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode8.3

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode8

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode7.3

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode6.4

    # BREW BUILDS
    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="zsh" BREW="zsh" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="ksh" BREW="ksh" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="mksh" BREW="mksh" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="dash" BREW="dash" TARGET="doc/spec/*"
      os:  osx
