language: bash
services:
  - docker

before_install:
  # Update brew catalogue if going to install anything
  - ${BREW:+brew update}
  - ${BREW:+brew install ${BREW}}

  # Build spec_doc module
  - ${spec_doc_shell} ./lib/dev module_assemble module_assemble module_assemble
  - ${spec_doc_shell} ./module_assemble spec_doc spec_doc
  - chmod +x spec_doc

script:
  - spec_doc_shell="${spec_doc_shell}" ${spec_doc_shell} ./spec_doc $(find ${TARGET})

matrix:
  include:
    # All Linux builds as docker images
    - env: LINUX_DOCKER= spec_doc_shell=sh TARGET="doc/test/*"
      os:  linux

    # OS X Targeted Builds
    - env: HIGH_SIERRA= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9.3

    - env: SIERRA= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9.2

    - env: SIERRA= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9.1

    - env: SIERRA= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode9

    - env: SIERRA= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode8.3

    - env: EL_CAPITAN= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode8

    - env: EL_CAPITAN= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode7.3

    - env: YOSEMITE= spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx
      osx_image: xcode6.4

    # BREW BUILDS
    - env: BREW="bash" spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx

    - env: BREW="zsh" spec_doc_shell="zsh" TARGET="doc/spec/*"
      os:  osx

    - env: BREW="ksh" spec_doc_shell="ksh" TARGET="doc/spec/*"
      os:  osx

    - env: BREW="mksh"spec_doc_shell="mksh"  TARGET="doc/spec/*"
      os:  osx

    - env: BREW="dash" spec_doc_shell="dash"  TARGET="doc/spec/*"
      os:  osx
