sudo: required
language: bash
services:
  - docker

before_install:
  # Update brew catalogue if going to install anything
  - ${BREW:+brew update}

  # Install brew dependencies
  - ${BREW:+brew install ${BREW}}

  # Build spec_doc module
  - ${spec_doc_shell} ./lib/dev module_assemble module_assemble module_assemble
  - ${spec_doc_shell} ./module_assemble spec_doc spec_doc
  - chmod +x spec_doc

script:
  - spec_doc_shell=${spec_doc_shell} ${spec_doc_shell} ./spec_doc $(find ${TARGET})

matrix:
  include:
    - env: spec_doc_shell=sh TARGET="doc/test/*"
      os:  linux

    - env: spec_doc_shell="bash" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="zsh" BREW="zsh" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="ksh" BREW="ksh" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="mksh" BREW="mksh" TARGET="doc/spec/*"
      os:  osx

    - env: spec_doc_shell="dash" BREW="dash" TARGET="doc/spec/*"
      os:  osx
