sudo: required
language: bash
services:
  - docker

env:
  - setup_prefix="docker run -v ${PWD}/workdir -w workdir -e"

before_install:
  # Install required apt packages
  - ${PPA:+${setup_prefix} ${IMAGE} add-apt-repository ppa:${PPA} -y}
  - ${APTGET:+${setup_prefix} ${IMAGE} apt-get update}
  - ${APTGET:+${setup_prefix} ${IMAGE} apt-get install -y ${APTGET}}

  # Install required yum packages
  - ${YUM:+${setup_prefix} ${IMAGE} yum -y update}
  - ${YUM:+${setup_prefix} ${IMAGE} yum -y ${APTGET}}

  # Install brew dependencies
  - ${BREW:+sudo update}
  - ${BREW:+sudo install ${BREW}}

  - echo "Using Setup '${setup_prefix}'"
  - echo "Using Shell '${spec_shell}'"

script:
  - spec_shell=${spec_shell} ${IMAGE:+${setup_prefix} }${spec_shell} ./coral spec

matrix:
  include:

    - env: IMAGE="ubuntu" spec_shell="bash-2.05b.13" APTGET="bash-2.05b.13" PPA="team-mayhem/multishell"
      os:  linux


    # Default shells in multiple distros
    - env: IMAGE="alpine" spec_shell="sh"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="sh"
      os:  linux

    - env: IMAGE="debian" spec_shell="sh"
      os:  linux

    - env: IMAGE="centos" spec_shell="sh"
      os:  linux

    - env: IMAGE="amazonlinux" spec_shell="sh"
      os:  linux

    - env: IMAGE="fedora" spec_shell="sh"
      os:  linux

    - env: IMAGE="opensuse" spec_shell="sh"
      os:  linux

    # Other shells (ubuntu only)
    - env: IMAGE="ubuntu" spec_shell="dash"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="bash"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="posh" APTGET="posh"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="mksh" APTGET="mksh"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="zsh" APTGET="zsh"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="pdksh" APTGET="pdksh"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="yash" APTGET="yash"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="ksh" APTGET="ksh"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="zsh-beta" APTGET="zsh-beta"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="busybox sh" APTGET="busybox"
      os:  linux






    - env: IMAGE="ubuntu" spec_shell="bash-3.0.16" APTGET="bash-3.0.16" PPA="team-mayhem/multishell"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="bash-3.1.9" APTGET="bash-3.1.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="bash-3.2.9" APTGET="bash-3.2.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="bash-4.1.9" APTGET="bash-4.1.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="bash-4.2.53" APTGET="bash-4.2.53" PPA="team-mayhem/multishell"
      os:  linux

    - env: IMAGE="ubuntu" spec_shell="bash-4.3.9" APTGET="bash-4.3.9" PPA="team-mayhem/multishell"
      os:  linux

    # Shells on OS X
    - env: spec_shell="bash"
      os:  osx

    - env: spec_shell="zsh" BREW="zsh"
      os:  osx

    - env: spec_shell="ksh" BREW="ksh"
      os:  osx

    - env: spec_shell="mksh" BREW="mksh"
      os:  osx

    - env: spec_shell="dash" BREW="dash"
      os:  osx
