sudo: required
language: bash
services:
  - docker

before_install:
  # Install PPA if environment requires it
  - ${PPA:+sudo add-apt-repository ppa:${PPA} -y}

  # Update apt catalogue if going to install anything
  - ${APTGET:+sudo apt-get update}

  # Install required apt packages
  - ${APTGET:+sudo apt-get install -y ${APTGET}}

  # Update brew catalogue if going to install anything
  - ${BREW:+brew update}

  # Install brew dependencies
  - ${BREW:+brew install ${BREW}}

  # Setup docker command for docker tests
  - target="${target:+docker run -v $(pwd)/workdir -w workdir -e spec_shell=${spec_shell} ${IMAGE} ${spec_shell}}"

script:
  - spec_shell=${spec_shell} ${target:-${spec_shell}} ./coral spec

matrix:
  include:
    - env: spec_shell="dash"
      os:  linux

    - env: spec_shell="bash"
      os:  linux

    - env: spec_shell="posh" APTGET="posh"
      os:  linux

    - env: spec_shell="mksh" APTGET="mksh"
      os:  linux

    - env: spec_shell="zsh" APTGET="zsh"
      os:  linux

    - env: spec_shell="pdksh" APTGET="pdksh"
      os:  linux

    - env: spec_shell="yash" APTGET="yash"
      os:  linux

    - env: spec_shell="ksh" APTGET="ksh"
      os:  linux

    - env: spec_shell="zsh-beta" APTGET="zsh-beta"
      os:  linux

    - env: spec_shell="busybox sh" APTGET="busybox"
      os:  linux

    - env: spec_shell="bash-2.05b.13" APTGET="bash-2.05b.13" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash-3.0.16" APTGET="bash-3.0.16" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash-3.1.9" APTGET="bash-3.1.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash-3.2.9" APTGET="bash-3.2.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash-4.1.9" APTGET="bash-4.1.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash-4.2.53" APTGET="bash-4.2.53" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash-4.3.9" APTGET="bash-4.3.9" PPA="team-mayhem/multishell"
      os:  linux

    - env: spec_shell="bash"
      os:  osx

    - env: spec_shell="zsh" BREW="zsh"
      os:  osx

    - env: spec_shell="ksh" BREW="ksh"
      os:  osx

    - env: spec_shell="mksh" BREW="mksh"
      os:  osx

    - env: spec_shell="dash" BREW="dash"
      os:  osx

    - env: IMAGE="alpine" spec_shell=sh
      os:  linux

    - env: IMAGE="ubuntu" spec_shell=sh
      os:  linux

    - env: IMAGE="debian" spec_shell=sh
      os:  linux

    - env: IMAGE="centos" spec_shell=sh
      os:  linux

    - env: IMAGE="amazonlinux" spec_shell=sh
      os:  linux
