version: "0.0.{build}"
os: Windows Server 2012 R2
build: off
deploy: off

install:
  # Update pacman if going to install anything
  - cmd: call %SHELLENV% -lc "${PACMAN:+pacman --needed --noconfirm -Sy pacman-mirrors}"
  - cmd: call %SHELLENV% -lc "${PACMAN:+pacman --noconfirm -Sy}"

  # Install pacman dependencies
  - cmd: call %SHELLENV% -lc "${PACMAN:+pacman --noconfirm -S $PACMAN}"

  # Build spec_doc module
  - cmd: call %SHELLENV% -lc "cd $APPVEYOR_BUILD_FOLDER; ${spec_doc_shell} ./lib/dev module_assemble spec_doc spec_doc"

test_script:
  - cmd: call %SHELLENV% -lc "cd $APPVEYOR_BUILD_FOLDER; spec_doc_shell=${spec_doc_shell} ${spec_doc_shell} ./spec_doc $(find doc/spec/*)"

environment:
  matrix:
    - spec_doc_shell: bash
      PACMAN: bash
      SHELLENV: C:\msys64\usr\bin\bash
    - spec_doc_shell: dash
      PACMAN: dash
      SHELLENV: C:\msys64\usr\bin\bash
    - spec_doc_shell: mksh
      PACMAN: mksh
      SHELLENV: C:\msys64\usr\bin\bash
    - spec_doc_shell: ksh
      PACMAN: ksh
      SHELLENV: C:\msys64\usr\bin\bash
    - spec_doc_shell: busybox sh
      PACMAN: busybox
      SHELLENV: C:\msys64\usr\bin\bash
    - spec_doc_shell: bash
      SHELLENV: C:\MinGW\msys\1.0\bin\sh
