#!/usr/bin/env sh

##
 # coral development version
 ##

# Portability options
. "./lib/module/support"

# require.sh variables and source
require_path="${require_path:-.:lib}"
require_loaded=' require.sh coral.sh '
. "./lib/require.sh"

# coral.sh source
. "./lib/coral.sh"

# module/entrypoint vairables and source
entrypoint='coral'
. "./lib/module/entrypoint"
