#!/usr/bin/env sh

##
 # require support — silently set sane options for all shells
 ##

# Options for all shells
#
# -e: Exit if any command has an uncaught error code
# -u: Exit on any use of an undefined variable
# -f: Do not expand glob patterns
set -euf

# Mimic local variables on ksh by aliasing it to typeset
#
# This command is ignored by shells other than ksh
#
if ( test -n "${KSH_VERSION:-}" &&
     test -z "${KSH_VERSION##*Version AJM*}" ) ||
     test -n "${YASH_VERSION:-}"
then
	alias local=typeset
elif test -n "${ZSH_VERSION-}"
then
	# Unset options for zsh to make it more portable
	#
	# NO_MATCH: Avoid expanding extra filename patterns
	# NO_SH_WORD_SPLIT: Make the word split on zsh behave like POSIX
	#
	# This command is ignored in shells other than zsh.
	#
	unsetopt GLOB NO_MATCH NO_SH_WORD_SPLIT >/dev/null 2>&1 || :
fi
