#!/bin/sh

##
 # lib/dev - Bootstraps and runs modules
 ##

dev_library_dir="$(cd "${0%/*}";printf %s "${PWD}")"

. "${dev_library_dir}/script/support"
. "${dev_library_dir}/require.sh"

entrypoint="${1:-false}"
entrypoint="${entrypoint%.sh}"
dev_library_file="$(echo "${entrypoint}" | sed 's|_|/|g').sh"
module_get_folder="${dev_library_dir}"
require_path="${require_path:-.:${dev_library_dir}}"
shift

require "${dev_library_file}"
require_loaded=' require.sh '
. "${dev_library_dir}/script/entrypoint"
